title: 'Fancy55'
email: ryan@fancy55.com
description: >
  Ryan Horricks

baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: # ginfuru
github_username: # ginfuru

color:
  - title: primary
    hex:  '#05E4E8'
    glow: '#424da6'
  - title: secondary
    hex:  '#ff9f26'
    glow: '#e83123'
  - title: accent
    hex:  '#E757FF'

# SEO
#image: # /assets/images/open_graph_image.png
google_analytics: UA-143092192-1

# Build settings
markdown: kramdown
incremental: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

    # Exclude from processing.
    # The following items will not be processed, by default. Create a custom list
    # to override the default setting.
exclude:
  - flightdeck.manifest.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package-lock.json # for those that use npm
  - package.json
  - README.md
  - vendor
  - yarn.lock # for those that use yarn
