title: 'Fancy55'
email: ryan@fancy55.com
description: >
  Ryan

baseurl: '/Fancy55' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: # ginfuru
github_username: # ginfuru

# SEO
#image: # /assets/images/open_graph_image.png
google_analytics: # UA-XXXXXXXX-XX -> https://minimalanalytics.com/

# Build settings
markdown: kramdown
incremental: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - flightdeck.manifest.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package-lock.json # for those that use npm
  - package.json
  - README.md
  - vendor
  - yarn.lock # for those that use yarn
